config/routes.rb
Rails.application.routes.draw do

  resources :cats
  resources :cat_rental_requests

  resources :cat_rental_requests do
  end
end

app/models/cat.rb
class Cat < ActiveRecord::Base

  validates :birth_date, :color, :name, :sex, presence: true
  validates :sex, inclusion: { in: ['M', 'F'] }

  has_many :cat_rental_requests,
    class_name: "CatRentalRequest",
    foreign_key: :cat_id,
    primary_key: :id,
    dependent: :destroy

end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base

  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :status, inclusion: { in: ['APPROVED', 'PENDING', 'DENIED'] }
  validate :request_validator

  def overlapping_requests
    CatRentalRequest.where.not(id: self.id)
      .where(cat_id: self.cat_id)
      .where.not("start_date > ? OR end_date < ?", self.end_date, self.start_date)
  end

  def approved_overlapping_requests
    overlapping_requests.where(status: 'APPROVED')
  end

  def overlapping_pending_requests
    overlapping_requests.where(status: 'PENDING')
  end

  def request_validator
    unless approved_overlapping_requests.empty?
      errors[:overlapping_request] << "Request overlaps with another"
    end
  end

  def approve!
    update(status: "APPROVED")
    save
    overlapping_pending_requests.each do |opr|
      opr.deny!
    end
  end

  def deny!
    update(status: "DENIED")
    save
  end

  def pending?
    self.status == 'PENDING' ? true : false
  end 

  belongs_to :cat,
    class_name: "Cat",
    foreign_key: :cat_id,
    primary_key: :id

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  def index
    @cat_rental_requests = CatRentalRequest.order(:start_date)
    render :index 
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end


end

app/controllers/cats_controller.rb
require 'date'


class CatsController < ApplicationController

  def age(cat)
    Date.today.year - cat.birth_date.year
  end

  def index
    @cats = Cat.order(:id)
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    render :new
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    cat = Cat.find(params[:id])
    if cat.update(cat_params)
      redirect_to cat_url(cat)
    else
      render json: cat.errors.full_messages, status: unprocessable_entity
    end
  end

  def destroy
    cat = Cat.find(params[:id])
    if cat.destroy
      redirect_to cats_url
    else
      render json: "Can't destroy this cat"
    end
  end

  def create
    cat = Cat.new(cat_params)
    if cat.save
      redirect_to cat_url(cat)
    else
      render json: cat.errors.full_messages, status: unprocessable_entity
    end
  end

  def cat_params
    params[:cat].permit(:name, :birth_date, :color, :sex, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cat_rental_requests/index.html.erb
<% @cat_rental_requests.each do |crr| %>
  <p><%= crr.cat.name %></p>
<% end %>

app/views/cats/_form.html.erb
<% url = persisted ? cat_url(cat) : cats_url %>
<% button_text = persisted ? "Update Cat" : "Create Cat" %>
<% cat_name = persisted ? cat.name : "" %>
<% cat_sex = persisted ? cat.sex : "" %>
<% cat_birth_date = persisted ? cat.birth_date : "" %>
<% cat_color = persisted ? cat.color : "" %>
<% cat_description = persisted ? cat.description : "" %>

<form action="<%= url %>" method="post">
  <% if persisted %>
    <input type="hidden" name="_method" value="patch">
  <% end %>

  <label for="cat_name">Name</label>
  <input id="cat_name" type="text" name="cat[name]" value="<%= cat_name %>"><br><br>

  <label>Sex<br>
    <% if cat_sex == "F" %>
    <input type="radio" name="cat[sex]" value="M"> Male<br>
    <input type="radio" name="cat[sex]" value="F" checked> Female<br>
    <% elsif %>
    <input type="radio" name="cat[sex]" value="M" checked> Male<br>
    <input type="radio" name="cat[sex]" value="F"> Female<br>
    <% end %>
  </label><br><br>

  <label for="cat_color">Color</label>
  <select id="cat_color" name="cat[color]">
    <option value="<%= cat_color %>" selected><%= cat_color %></option>
    <option value="Black">Black</option>
    <option value="White">White</option>
    <option value="Silver">Silver</option>
    <option value="Gold">Gold</option>
    <option value="Yellow">Yellow</option>
    <option value="Brown">Brown</option>
    <option value="Grey">Grey</option>
    <option value="Orange">Orange</option>
    <option value="Tortoiseshell">Tortoiseshell</option>
    <option value="Mackerel">Mackerel</option>
    <option value="Siamese">Siamese</option>
  </select><br><br>


  <label for="cat_birth_date">Birth Date</label>
  <input id="cat_birth_date" type="date" name="cat[birth_date]" value="<%= cat_birth_date %>"><br><br>

  <label for="cat_description">Description</label>
  <input type="textarea" id="cat_description" name="cat[description]" value="<%= cat_description %>"><br><br>

  <input type="submit" value="<%= button_text %>">
</form>

app/views/cats/edit.html.erb
<h1>Edit Cat</h1>

<%= render 'form', persisted: true, cat: @cat %>

app/views/cats/index.html.erb
<h1>99 Cats</h1>
<table>
  <tr>
    <th>Name</th>
    <th>Color</th>
    <th>Birth Date</th>
    <th>Sex</th>
  </tr>
  <% @cats.each do |cat| %>
  <tr>
    <td><a href="<%= cat_url(cat) %>"><%= cat.name %></a></td>
    <td><%= cat.color %></td>
    <td><%= cat.birth_date %></td>
    <td><%= cat.sex %></td>
  </tr>
  <% end %>
</table>

app/views/cats/new.html.erb
<h1>New Cat</h1>

<%= render 'form', persisted: false, cat: @cat %>

app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>
<%= button_to "Delete Cat", cat_url(@cat), method: :delete %>
<%= button_to "Edit Cat", edit_cat_url(@cat), method: :get %><br>
<table>
  <tr>
    <th>Name</th>
    <th>Color</th>
    <th>Birth Date</th>
    <th>Sex</th>
  </tr>
  <tr>
    <td><%= @cat.name %></td>
    <td><%= @cat.color %></td>
    <td><%= @cat.birth_date %></td>
    <td><%= @cat.sex %></td>
  </td>
</table>

<h3>Description</h3>
<p><%= @cat.description %></p>

<h3>Rental Requests</h3>
<ul>
<% @cat.cat_rental_requests.order(:start_date).each do |rr| %>
  <li><%= rr.start_date %> <%= rr.end_date %> <%= rr.status %></li>
  <% if rr.pending? %>
    <%= button_to "Approve Rental Request", cat_url(@cat), method: :delete %>
    <%= button_to "Deny Rental Request", cat_url(@cat), method: :delete %>
  <% end %>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NinetyNineCats</title>
  <!-- <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %> -->
  <!-- <%#= javascript_include_tag 'application', 'data-turbolinks-track' => true %> -->
  <!-- <%#= csrf_meta_tags %> -->
</head>
<body>

<%= yield %>

</body>
</html>